### ISSUE TITLE
Docker image of the app

### ISSUE THREAD

**Issue by boloson** [girke-lab/chemminetools#162]
Would it be possible to create a docker container for this app?

**Comment by TylerBackman** [comment]
Hello @boloson, an updated version of ChemMine Tools is in the planning stages, which will utilize a series of docker containers via docker compose. Unfortunately, that isn't ready yet but please check back in 6 months or so. I know the current vagrant container is difficult to build, because it pulls from external databases that have changed substantially since it was first built. 

@tgirke

**Comment by amarpreetsaini** [comment]
@TylerBackman Is there any vagrant images for aws or a docker Image for tool?

**Comment by TylerBackman** [comment]
@amarpreetsaini A docker image is under development. It would also be possible to adapt the current vagrant setup to AWS, but we don't have that already.
