### ISSUE TITLE
MCS Tanimoto Coefficient is incorrect...

### ISSUE THREAD

**Issue by complext** [girke-lab/chemminetools#172]
Hello,

I have been perusing your tool at chemminetools.ucr.edu to evaluate its MCS Tanimoto Coefficient computing capability, but in comparing this to the popular and well-supported platform RDKit, I see that your Tanimoto coefficients consistently differ, both for the Atom Pair and Maximum Common Substructure definitions. 

As an example:
![0](https://user-images.githubusercontent.com/52838908/61497521-8c7fd880-a974-11e9-9201-6278ff243dc6.png)
![1](https://user-images.githubusercontent.com/52838908/61497524-90135f80-a974-11e9-9f15-6ff9847217c5.png)
These 2 structures return a AP Tanimoto value of over 0.4, whilst in RDKit, they return a value substantially below 0.3. The MCS Tanimoto value is 0.6 in Chemminer, with the MCS shown as benzene. But when I compute the Tanimoto coefficient in RDKit between any of the 2 structures above and benzene, I obtain a value less than 0.2. Similarly, RDKit's MCS identifier finds the MCS to be:
![2](https://user-images.githubusercontent.com/52838908/61497728-627ae600-a975-11e9-9992-9848419d014a.png)
rather than benzene (shown below).
![3](https://user-images.githubusercontent.com/52838908/61497738-6dce1180-a975-11e9-8887-35aa1aff3052.png)

Please advise.

**Comment by tgirke** [comment]
Comparing the absolute values of Tanimoto coefficients among different software tools is only valid if they use the exact same algorithms for computing the underlying structural fragments that are used for structural similarity computations. Whether RDKit uses in these cases the same algorithms as ChemMine Tools, I am not sure. For instance, in case of MCS there are many different algorithms that are not guaranteed to find the exact same subgraphs in compounds. Slight differences in the methods used for assigning aromaticity to subgraphs can be another reason. Similarly, for atom pairs (AP) there can be differences in how they are extracted and then used for calculating the Tanimoto coefficients. Sometimes the variable length AP vectors are converted into fingerprints, while this is not the case in other implementations often resulting in substantial differences in the final Tanimoto coefficients. Since the calculation of the Tanimoto coefficient itself is rather simple, differences in the underlying fragment extraction are more likely to be the source of the differences you are observing. - I hope this makes sense.
