### ISSUE TITLE
Error while adding a large set of compounds by CIDs

### ISSUE THREAD

**Issue by daenbol** [girke-lab/chemminetools#190]
Hello! Maybe there are too many compounds with complicated structure, should I exclude something from a list? Here is my list of CIDs:
186907
5280389
73360
500027
118701473
443678
72376
72378
443689
11876135
441593
5289124
72392
441306
482108
36294
123865
165580
3081545
3467
20054942
71461381
439530
6438814
24180439
102596141
54675783
129395
54671203
276389
285033
65305
16134395
429598
10254449
72505
72504
135398689
5351572
11669726
15940571
15940571
120760
245940
245940
6197
73396
91467
145721258
5363794
5363794
177936
25223631
5324556
54688606
54676871
127675
10549927
512882
253602
11790817
6326658
23305159
101627277
5381287
11692946
23426006
11060358
10345974
379085
446232
42640128
269624
5235
72646
72299
171612
175985
137348262
170012
11226719
28675
125665
170723
129552
25215756
441139
5281394
5478005
16040283
65380
9543443
6436444
6444170
9576884
6438817
9576795
6105995
54683011
71748056
54602813
5458870
5281304
73432
6436238
134025
315123
72965
432922
122785
99530
127805
14060344
70697724
9985020
10745249
6436226
6474271
6436229
441789
3000796
460525
460524
6451123
72956
72952
6436227
274265220
460522
6436228
6436225
6451089
72961
441791
225484
72964
441803
182704
102267540
101665330
185611
12313355
182116
46173860
101921953
65571
460536
460540
5281311
158475
5458871
4046
202225
12444502
5369716
6437832
23305158
9915017
107974
91518
5284461
12315016
6711209
13797589
91518
14218252
546103
304599
40024
5284433
102515038
6326658
73050
13818797
189939
92114
402628
92765
246845
92114
439647
11118411
117729068
42831
102439777
11219835
2161
71748051
428489
11735014
131917
1227681
794138
41673734

**Comment by daenbol** [comment]
The previous issue from Fxotics was checked, now I am trying to input compounds by sdf file. Here is my new problem: ERROR: Database error, possibly excessively large compound?

**Comment by daenbol** [comment]
Max mw of my compounds is 724 Da, not so big...

**Comment by tgirke** [comment]
To download compounds from Pubchem into your workbench you need to provide smaller batches since they don't allow to download too many at once. If there are problems with a SDF file upload to Chemmine Tools directly then please provide a URL to that file (e.g. on Dropbox, Box, GoogleDrive or similar) so that we can download it and take a look.

**Comment by daenbol** [comment]
Here is a link https://drive.google.com/file/d/1Q5Jer8NizzBzpUuokC0zhNrGP1Xjz-hC/view?usp=sharing

**Comment by tgirke** [comment]
There seems to be a problem with some special characters or unusual formatting in the datablocks of the compounds in your SDF file. When I clean up in ChemmineR (here truncate) the datablocks in your SDF then the upload on ChemMine Tools works. The code for cleaning up your SDF in [ChemmineR](https://bioconductor.org/packages/release/bioc/html/ChemmineR.html) is given below. Possibly the same formatting issue causes the problem when loading the compounds via Pubchem IDs since they will be passed on as SDFs. We could look into how to debugging this formatting issue.
ChemmineR code from vignette [here](https://bioconductor.org/packages/release/bioc/vignettes/ChemmineR/inst/doc/ChemmineR.html). Note, ChemmineR is part of the ChemMine Tools project but requires some very basic R knowledge.
 
```r
library(ChemmineR)                                                                                                                                                                  
sdfset <- read.SDFset("2410020334813654525.sdf")                                                                                                                                    
datablock(sdfset) <- sdfid(sdfset)                                                                                                                                                  
write.SDF(sdfset, "clean_datablock.sdf")                                                                                                                                            
# -> upload of 'clean_datablock.sdf' works 
```
